[package]
name = "futures-tutorial"
version = "0.1.0"
authors = ["Sujay Jayakar <sujayakar314@gmail.com>"]

[dependencies]
crossbeam-channel = "0.1.2"

hex = "0.2.0"
futures = "0.1.17"
futures-cpupool = "0.1.8"
rust-crypto = "0.2.36"

[profile.release]
opt-level = 3
panic = "abort"